@api = http://localhost:3000/api

GET {{api}}/races

###
GET {{api}}/races/ID

### Create a video
POST {{api}}/races
Content-Type: application/json

{ }

###
DELETE {{api}}/races/ID

###
PUT {{api}}/races/ID